apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.odeApiSignalStatus.name }}
data:
  appsettings.Production.json: |
    {
      "Authentication": {
          "Authority": "{{ .Values.url.identity }}"
      },
      "Kafka": {
          "bootstrap": {
              "servers": "{{ .Values.kafka.server }}"
          },
          "ssl": {
            "ca": "{{.Values.kafka.ca}}",
            "certificate": "{{.Values.kafka.certificate}}"
          },
          "sasl": {
              "mechanism": "{{.Values.kafka.security.mechanism}}",
              "username": "{{.Values.kafka.userName}}"
          },
          "security": {
               "protocol": "{{.Values.kafka.security.protocol}}"
          },
          "groupId": "{{ .Values.odeApiSignalStatus.kafka.groupId }}"
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.odeApiSignalStatus.name }}
  labels:
    app: {{ .Values.odeApiSignalStatus.name }}
    chart: {{ .Values.odeApiSignalStatus.name }}
    release: {{ .Release.Name }}

  annotations:
 
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.odeApiSignalStatus.name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.odeApiSignalStatus.name }}
     
        release: {{ .Release.Name }}
      annotations:

    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              release: {{ .Release.Name }}
      imagePullSecrets:
        - name: {{ .Values.secrets.imagePullSecret }}
      volumes:
        - name: config
          configMap:
            name: {{ .Values.odeApiSignalStatus.name }}
      containers:
        - name: {{ .Values.odeApiSignalStatus.name }}
          image: "cosysdev.azurecr.io/ode-api-signal-status:{{ .Values.odeApiSignalStatus.imageTag }}"
          imagePullPolicy: Always
          env:
            - name: Kafka__sasl__password
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.kafka.userName }}
                  key: password
            - name: ConnectionStrings__Redis
              valueFrom:
                secretKeyRef:
                  name: redis-cs
                  key: RedisConnection
          volumeMounts:
            - name: config
              mountPath: /app/appsettings.Production.json
              subPath: appsettings.Production.json
              readOnly: true
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
{{ toYaml .Values.odeApiSignalStatus.resources | indent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.odeApiSignalStatus.name }}
  labels:
    app: {{ .Values.odeApiSignalStatus.name }}
    chart: {{ .Values.odeApiSignalStatus.name }}
    release: {{ .Release.Name }}
 
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.odeApiSignalStatus.name }}
    release: {{ .Release.Name }}